// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/31/2025, 8:19:37 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/plugins/**/*.{js,ts,mjs}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/composables/**/*.{js,ts,mjs}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/utils/**/*.{js,ts,mjs}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["25"] = "/Users/eduardlupacescu/Sites/binarcode/laravel-restify/docs-v3/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;