<template>
  <div class="w-full max-w-4xl mx-auto px-4 py-8 hidden md:block">
    <!-- Main container showing One Codebase → Two Outputs -->
    <div class="relative flex items-center justify-between">
      <!-- Center - One Codebase (Laravel Models) -->
      <div class="flex flex-col items-center space-y-2">
        <div class="relative">
          <!-- Laravel/Database icon representing the single codebase -->
          <div class="w-16 h-16 bg-gradient-to-br from-primary-500 to-primary-600 rounded-xl flex items-center justify-center shadow-lg">
            <Database :size="32" class="text-white" />
          </div>
          <!-- Pulsing effect to show it's the source -->
          <div class="absolute inset-0 rounded-xl bg-primary-400 opacity-20 animate-pulse"></div>
        </div>
        <div class="flex flex-col gap-1">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white text-center">One Codebase</h3>
          <p class="text-sm text-gray-600 dark:text-gray-400 text-center">Laravel Models</p>
        </div>
      </div>

      <!-- Animated branching lines -->
      <div class="flex-1 relative px-8">
        <!-- Top branch to REST API -->
        <div class="relative mb-4">
          <div class="h-0.5 bg-gradient-to-r from-transparent to-primary-500 transition-all duration-[2s] ease-out"
               :style="{ width: topBranchWidth }"></div>
        </div>
        
        <!-- Bottom branch to MCP Server -->
        <div class="relative">
          <div class="h-0.5 bg-gradient-to-r from-transparent to-primary-500 transition-all duration-[2s] ease-out"
               :style="{ width: bottomBranchWidth }"></div>
        </div>
      </div>

      <!-- Right side - Two Outputs -->
      <div class="flex flex-col space-y-6">
        <!-- REST API Output -->
        <div class="flex items-center space-x-3 transition-all duration-500">
          <div class="w-12 h-12 bg-gradient-to-br from-blue-100 to-blue-200 dark:from-blue-900 dark:to-blue-800 rounded-xl flex items-center justify-center shadow-md">
            <Users :size="24" class="text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h4 class="text-base font-semibold text-gray-900 dark:text-white">REST API</h4>
            <p class="text-xs text-gray-600 dark:text-gray-400">For Humans</p>
          </div>
        </div>

        <!-- MCP Server Output -->
        <div class="flex items-center space-x-3 transition-all duration-500">
          <div class="w-12 h-12 bg-gradient-to-br from-emerald-100 to-emerald-200 dark:from-emerald-900 dark:to-emerald-800 rounded-xl flex items-center justify-center shadow-md">
            <Bot :size="24" class="text-emerald-600 dark:text-emerald-400" />
          </div>
          <div>
            <h4 class="text-base font-semibold text-gray-900 dark:text-white">MCP Server</h4>
            <p class="text-xs text-gray-600 dark:text-gray-400">For AI Agents</p>
          </div>
        </div>
      </div>
    </div>

    <!-- "Automatically Generated" indicator -->
    <div class="text-center mt-6">
      <div class="inline-flex items-center px-3 py-1 rounded-full bg-green-100 dark:bg-green-900 transition-opacity duration-500"
           :style="{ opacity: showAutoGenerated ? 1 : 0 }">
        <Sparkles :size="14" class="text-green-600 dark:text-green-400 mr-1" />
        <span class="text-xs font-medium text-green-700 dark:text-green-300">Automatically Generated</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Users, Bot, Database, Sparkles } from 'lucide-vue-next'

const topBranchWidth = ref('0%')
const bottomBranchWidth = ref('0%')
const showTopEndpoint = ref(false)
const showBottomEndpoint = ref(false)
const highlightRest = ref(false)
const highlightMcp = ref(false)
const showAutoGenerated = ref(false)

let animationTimeout: NodeJS.Timeout | null = null

function resetAnimationState() {
  topBranchWidth.value = '0%'
  bottomBranchWidth.value = '0%'
  showTopEndpoint.value = false
  showBottomEndpoint.value = false
  highlightRest.value = false
  highlightMcp.value = false
  showAutoGenerated.value = false
}

function animateBranches() {
  setTimeout(() => {
    topBranchWidth.value = '100%'
    bottomBranchWidth.value = '100%'
  }, 500)
}

function showEndpoints() {
  setTimeout(() => {
    showTopEndpoint.value = true
    showBottomEndpoint.value = true
    highlightRest.value = true
    highlightMcp.value = true
  }, 2000)
}

function showCompletionMessage() {
  setTimeout(() => {
    showAutoGenerated.value = true
  }, 2000)
}

function startAnimation() {
  resetAnimationState()
  animateBranches()
  showEndpoints()
  showCompletionMessage()
}

function initializeAnimation() {
  startAnimation()
}

function cleanup() {
  if (!animationTimeout) return
  
  clearTimeout(animationTimeout)
}

onMounted(initializeAnimation)
onUnmounted(cleanup)
</script>

<style scoped>
.transition-all {
  transition-property: all;
}

.duration-3000 {
  transition-duration: 3s;
}

@keyframes float {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-10px); }
}

.animate-float {
  animation: float 3s ease-in-out infinite;
}
</style>
