name: Psalm

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    psalm:
        name: psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
              with:
                  persist-credentials: false

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: '8.4'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Cache composer dependencies
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}

            - name: Run composer install
              run: composer install -n --prefer-dist

            - name: Run psalm
              run: ./vendor/bin/psalm --output-format=github
