name: Psalm

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    psalm:
        name: psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: '8.4'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Cache composer dependencies
              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}

            - name: Run composer install
              run: composer install -n --prefer-dist

            - name: Run psalm
              run: ./vendor/bin/psalm --output-format=github
